### ISSUE TITLE
Ted2/debugger crash

### ISSUE THREAD

**Issue by DruggedBunny** [blitz-research/monkey2#194] opened 2017-07-22 17:31 UTC
I haven't yet dug into what's wrong with my code (not used stacks before!), but if I run this, it says that _cubes.Push (cube)_ is invoking on a null instance, no doubt correctly.

If I then click on the cube entry in the debugger (see screenshot, highlighted in red -- think I have to click twice), it crashes Ted2. Using last itch.io release...

```
#Import "<std>"
#Import "<mojo>"
#Import "<mojo3d>"

Using std..
Using mojo..
Using mojo3d..

' ----------------------------------------
' Application name...
' ----------------------------------------

Global AppName:String = "My 3D Game"

' ----------------------------------------
' Radians to degrees helper...
' ----------------------------------------

Global RadDivider:Float = Pi / 180.0

Function Degrees:Float (radian:Float)
	Return radian * RadDivider
End

' ----------------------------------------

Function CreateCube:Model (color:Color = Color.Aluminum)

	Local cube:Model
	Local cubemesh:Mesh
	Local cubematerial:Material

	cubemesh		= Mesh.CreateBox (New Boxf (-0.5, 0.5, 0.5, 0.5, -0.5, -0.5))
	cubematerial	= New PbrMaterial (color)
	
	cube = New Model (cubemesh, cubematerial)

	Return cube
			
End

Class Game Extends Window
	
	' Basic 3D scene requirements...
	
	Field scene:Scene
	Field camera:Camera
	Field light:Light

	Field cubes:Stack<Model>
	
	'Field cube:Model
	'Field cubemesh:Mesh
	'Field cubematerial:Material
	
	Method New (title:String, width:Int, height:Int, flags:WindowFlags)
		
		Super.New (title, width, height, flags)
		
		scene 	= Scene.GetCurrent () ' Important!
		
		camera	= New Camera

		light	= New Light

			light.Move (-50, 50, 0)
			light.Rotate (0, Degrees (90), 0)
		
		For Local loop:Int = 1 To 100
			
			Local cube:Model = CreateCube ()
			
			cube.Move (Rnd (-100, 100), Rnd (-100, 100), Rnd (-100, 100))
			
			cubes.Push (cube)
			
		Next
		
	End
	
	Method OnRender (canvas:Canvas) Override

		For Local cube:Model = Eachin cubes
			cube.Rotate (Degrees (0.1), Degrees (0.2), Degrees (0.4))
		next
		
		scene.Render (canvas, camera)
		
		RequestRender ()
		
	End
	
End

Function Main ()

	' Windowed mode...
	
	Local width:Int			= 640
	Local height:Int		= 480
	Local flags:WindowFlags	= WindowFlags.Center
	
	New AppInstance
	
	New Game (AppName, width, height, flags)
	
	App.Run ()
		
End
```

https://s21.postimg.org/o0l1u8irb/debuggercrash.png

**Comment by blitz-research** [comment] 2017-07-23 00:53
I can't reproduce this with either the latest develop branch or the latest
build at itch.io (v1.1.05b).

In v1.1.05b, you have to click the stop button twice as the first click
only activates the window, second kills the app.

This is fixed in the latest develop branch and one click kills the app.

Does the debugger work for you at all, eg: can you try an array index error
or something?

And I'm assuming this is on PC...

**Comment by abakobo** [comment] 2017-07-23 16:44
Do you know that mx2 development environment is supported on W10(PC) and from ElCapitan(Mac)?
So if you have this crash on W7 this is "normal" as stated by mark several months ago. On my W7 it has always crashed.. on W10 not.

**Comment by DruggedBunny** [comment] 2017-07-23 23:20
Oh... good point, abakobo. I'm on Windows 7, but now you mention it, I do recall Mark saying '10 would be required.

Here it is anyway, with an array index error:

https://www.youtube.com/watch?v=6nV-4Dn0yx0

Guess I just have to work around this sort of thing! Not touching Windows 10 with a bargepole, absolutely hated it.

If this is expected/undefined for Windows < 10 then fine to close this one off, I guess!

**Closed as completed** 2017-08-25 22:39 UTC
