### ISSUE TITLE
Ted2go kaypad issue

### ISSUE THREAD

**Issue by EdzUp** [blitz-research/monkey2#191] opened 2017-07-03 11:08 UTC
Using the keypad without numlock still adds numbers to the source code, for example pressing PgDn does page down but inserts a 3 as well. This goes for all the other keys as well on the keypad.

**Comment by blitz-research** [comment] 2017-07-10 22:12
I can't reproduce this on Windows 10 with monkey2-v1.1.05b.

Please provide more details of your setup.

Anyone else having this problem?

**Comment by EdzUp** [comment] 2017-07-10 23:06
I'm using v1.1.0.4 I will update and see if it helps.

**Comment by RichardBetson** [comment] 2017-07-12 02:26
Using v1.104 and have this issue. Numlock on has issues placing numbers on other lines (then intended). It's as if numlock is on and off entering numbers and navigating (page up/down) at the same time. Last I checked 1.105 was not a release here on github, still I'll try the latetest Monkey 2 version here soon to see if it is still an issue. 

Running Linux Mint 17.2 here.

**Comment by blitz-research** [comment] 2017-07-12 02:34
Most of the action is taking place in the develop branch these days, so you
will need to rebuild that on linux for the latest stuff.

**Comment by RichardBetson** [comment] 2017-07-21 02:31
This looks to be fixed in v1.1.0.5c.. FYI.

**Closed as completed** 2017-07-28 02:15 UTC
