### ISSUE TITLE
Emscripten Double overwrites variable declared before it.

### ISSUE THREAD

**Issue by Pakz001** [blitz-research/monkey2#128] opened 2016-12-09 10:56 UTC
I had a double set up in a class. I noticed in emscripten that the value declared right before the Double got set to zero. It happens when I wrote the millisecs() to the double variable. When I changed the double to int, the overwrite did not happen.

**Comment by blitz-research** [comment] 2017-01-11 22:35
Can you please post some sample code?

**Comment by Pakz001** [comment] 2017-01-12 04:02
`' bug in emscripten debug/runtime
#Import "<std>"
#Import "<mojo>"

Using std..
Using mojo..

Class test
	Field a:Int
	Field b:Int
	Field c:Double	
End Class 

Global mytest:test = New test


Class MyWindow Extends Window

	Method New()
	
	End Method
	
	Method OnRender( canvas:Canvas ) Override
		App.RequestRender() ' Activate this method 
		'		
		mytest.a=300
		mytest.b=400 ' this one gets put to ZERO			
		mytest.c=500
		
		'
		canvas.DrawText(mytest.a,100,120)
		canvas.DrawText(mytest.b,100,140)
		canvas.DrawText(mytest.c,100,160)
		' if key escape then quit
		If Keyboard.KeyReleased(Key.Escape) Then App.Terminate()		
	End Method	
	
End	Class

Function Main()
	New AppInstance		
	New MyWindow
	App.Run()
End Function`

**Comment by blitz-research** [comment] 2017-01-12 22:40
Thanks!

Very weird bug, can't reproduce it in plain c++ as yet, but it does seem to
be an emscripten only issue. Will keep hacking.

**Comment by blitz-research** [comment] 2017-12-18 01:14
Fixed in develop!

**Closed by blitz-research** 2017-12-18 01:14 UTC
