### ISSUE TITLE
Mojo3d sprites don't render correctly with fog

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#265] opened 2017-11-12 06:59 UTC
Sprites simply assume the far color of the fog, and if a model is behind them, they seem to render with that model's fog intensity.

In the code below, replace the sprite texture with any texture you have handy:
```

#Import "<mojo3d>"
#Import "<std>"

#Import "images/cat.png"

Using mojo3d..
Using mojo..
Using std..

Function Main()
	New AppInstance
	New TestWindow
	App.Run()
End

Class TestWindow Extends Window
	
	Field cam:Camera
	Field cube:Model
	
	Method New()
		Super.New( "Test", 960, 540, WindowFlags.Resizable )
		ClearColor = Color.Black
		
		Local spriteMat := SpriteMaterial.Load( "asset::cat.png" )
		For Local x := -2 To 2
			For Local y := -2 To 2
				Local sprite := New Sprite( spriteMat )
				sprite.SetPosition( x, 0, y )
			Next
		Next
		
		cube = Model.CreateBox( New Boxf(-4,-15,-0.2,4,15,0.2), 1, 1, 1, New PbrMaterial( Color.Red ) )
		cube.Move( 0,0,5)
		
		cam = New Camera
		cam.SetPosition( 0, 1, -3 )
		cam.Near = 0.1
		cam.Far = 10.0
		cam.PointAt( New Vec3f )
		
		Local fog := New FogEffect( Color.Orange, cam.Near, cam.Far )
		Scene.GetCurrent().AddPostEffect( fog )
	End
	
	Method OnRender( canvas:Canvas ) Override
		RequestRender()
		
		cube.SetPosition( Sin(Millisecs()/1000.0)*6, 0, Cos(Millisecs()/1000.0)*6 )
		
		Scene.GetCurrent().Render( canvas, cam )
		canvas.DrawText( "Width="+Width+", Height="+Height+", FPS="+App.FPS,0,0 )
	End
End
```

**Comment by blitz-research** [comment] 2017-11-12 22:08
Woah, not quite sure what I'm looking at there! I get a weird 'windscreen
wiper' effect that looks like it might be something being clipped, and some
psychadelic 'pulse' lighting and fuzzy sprites popping in and out of view!

I added this to mojo3d/tests/sprites.monkey2...

```
_fog=New FogEffect
_fog.Near=0
_fog.Far=100
_scene.AddPostEffect( _fog )
```
...just after _scene.SkyTexture=... and everything seems to work as I would
have expected.

Can you duplicate your issue with a slightly less mind altering example?

**Comment by DoctorWhoof** [comment] 2017-11-13 03:20
Hah hah, sorry, I didn't mean to induce a drug-free trip!

The example just shows - I my machine, at least - how the sprites don't render at all when the fog is present, unless a piece of geometry, the rotating cube, passes behind them. You can turn off the fog to see where all the sprites "should" be rendered.

The sprites banana with the modified code you sent seems to work at first, but just because there's geometry behind the sprites. Once you place the camera so that a sprite is against the bg, you can see the problem - at least in my MacBook/MacOS high Sierra laptop.

Here's a screenshot:
<img width="752" alt="screen shot 2017-11-12 at 7 18 42 pm" src="https://user-images.githubusercontent.com/6250116/32708400-8e24a810-c7de-11e7-9396-e24526db9cb2.png">

**Comment by blitz-research** [comment] 2017-11-13 04:30
> Hah hah, sorry, I didn't mean to induce a drug-free trip!

No complaints here, just don't expect me to get much work done!

Well, I can 'fix' this but to do so I'll  need to enable alpha masking, ie:
discard pixels with alpha<0.5 or something.

The problem is that for sprites to play nicely with fog they also need to
writre to the depth buffer. However, in the case of 'non-square' sprites
like my tree sprite, this means you end up with a mysterious 'rect of fog'
around each sprite!

But I had a quick go at alpha masking and the results seem fine with my
test sprite scene - will push a fix soon, just have some other stuff I've
been tinkering with to clean up.

**Comment by blitz-research** [comment] 2017-11-19 21:51
This is semi-fixed in the latest develop code - SpriteMaterial has a new 'AlphaDiscard' property that allows you to modify a sprite's 'alpha masking' level. It defaults to 0.5 which means any sprite texels with alpha <0.5 will be discarded entirely, ie: they wont render to the color OR depth buffers.

Mojo3d currently implements fog as a post processing pass, which is flexible but means fog happens after blending and depends purely on the depth in the depth buffer so to prevent sprites generating ghostly 'foggy rects' you have to prevent 'empty' texels (ie: alpha=0 (or <.5 etc)) texels from being renderered or they end up affecting the depth buffer even though they don't apparently render anything.

The alternative to this would be to implement the fog algorithm inside every shader so fog happens *before* blending. This makes it much harder to modify the fog algorithm etc though as you need to modify each shader, and it makes each shader less 'independent'. I'm prepared to do this if necessary but will be sticking with the current approach for now as it may be good enough or I may have another idea!

**Closed as completed by blitz-research** 2017-11-19 21:51 UTC
