### ISSUE TITLE
Some gLTF models load "inside out" and have light inverted

### ISSUE THREAD

**Issue by Hezkore** [blitz-research/monkey2#305] opened 2017-12-31 01:23 UTC
I have a mesh that loads "inverted" in Monkey 2, but is fine in every other loader and viewer.
The normals also seem to be inverted, as lightning points the wrong way.

Here it is in Blender, with everything looking good:
![Blender](https://user-images.githubusercontent.com/1727541/34458378-db86fbb8-edd0-11e7-8da6-b0c5c818ea45.gif)

Here it is in Win10's default gLTF viewer, which also looks okay:
![Win10](https://user-images.githubusercontent.com/1727541/34458384-1b0f2f1c-edd1-11e7-91ea-3513a7cd6fed.gif)

Here it is in donmccurdy's online gLTF-viewer, once again looking good:
(https://gltf-viewer.donmccurdy.com/)
![gltf-viewer.donmccurdy](https://user-images.githubusercontent.com/1727541/34458386-29abdcc8-edd1-11e7-82f4-efb2459a5809.gif)

Here it is in Monkey 2:
![Monkey2](https://user-images.githubusercontent.com/1727541/34458395-565d87e4-edd1-11e7-997d-5b01857ea25a.gif)
As you can see, the model is inverted and the lightning should be coming from above, not below it.
Even if you flip the mesh the lightning is still wrong.

![Light](https://user-images.githubusercontent.com/1727541/34458399-8bd869a2-edd1-11e7-91fa-7d6864f4c1c1.png)

I'm not sure if I'm to blame here, since I'm not very good with 3D.
And maybe the other viewers detects things like this and fixes it for me?
But I thought I'd report it anyways since it seems to differ from what every other viewer and loader does.

Here's the model itself and some code to demonstrate the issue.
[Example](https://github.com/blitz-research/monkey2/files/1594912/invMesh.zip)

**Comment by blitz-research** [comment] 2017-12-31 01:59
The problem is due to the gltf model having negative scale factors - a new
one on me!

All x,y,z components of scale are negative, and when you perform an 'odd
number' of negative axial scales, you effectively turn a model 'inside
out'. And off course, when you negate a normal, it swaps up/down etc, so
model appears to lit from entirely the wrong direction!

I have fixed this in the develop branch by using abs() on scale components
in the gltf loader. I assume this is what other loaders do, or some
variations off, but I suggest you stick with positive scales if possible.

**Comment by blitz-research** [comment] 2017-12-31 02:05
Ok, according to the gltf2 spec, negative scales are possible but:

"If the determinant of the transform is a negative value, the winding order
of the mesh triangle faces should be reversed. This supports negative
scales for mirroring geometry."

However, normals/tangents will still be pointed in the wrong direction so
this wont fix the upside-down lighting problem (so I assume it's intended
for unlit geometry anyway). I'll look at implementing this in future (make
an issue if you *really* want this!) but for now try to stick with positive
scales.

**Comment by Hezkore** [comment] 2017-12-31 07:13
Ah okay!
I didn't make the mesh, so everything looked fine to me.
I remade the mesh myself, and it instantly worked.

Your solution is fine by me, but maybe leave the issue open as the solution isn't according to the gLTF specs?
Or just write it down somewhere heh.

**Comment by blitz-research** [comment] 2018-01-23 02:07
I'm calling this 'fixed'.

**Closed as completed by blitz-research** 2018-01-23 02:07 UTC
